wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.20
    framework: torch
    is_jupyter_run: false
    python_version: 3.5.2
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 10
log_interval:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.5
no_cuda:
  desc: null
  value: false
seed:
  desc: null
  value: 1
test_batch_size:
  desc: null
  value: 1000
